// 5 theme definitions — each maps CSS variable names to values.
// Applied to document.documentElement via ThemeContext.

export const themes = [
  {
    id: 'executive-dark',
    name: 'Executive Dark',
    label: 'Dark',
    vars: {
      '--bg-primary':      '#0f1117',
      '--bg-secondary':    '#1a1d27',
      '--bg-card':         '#1e2130',
      '--bg-hover':        '#252840',
      '--border':          '#2e3148',
      '--text-primary':    '#f1f5f9',
      '--text-secondary':  '#94a3b8',
      '--text-muted':      '#64748b',
      '--accent':          '#6366f1',
      '--accent-light':    '#818cf8',
      '--accent-bg':       'rgba(99,102,241,0.12)',
      '--chart-1':         '#6366f1',
      '--chart-2':         '#8b5cf6',
      '--chart-3':         '#06b6d4',
      '--chart-4':         '#10b981',
      '--chart-5':         '#f59e0b',
      '--shadow':          '0 4px 24px rgba(0,0,0,0.4)',
      '--glass':           'none',
      '--sidebar-bg':      '#13151f',
      '--header-bg':       '#13151f',
      '--geo-land-data':   '#2d3561',
    },
  },
  {
    id: 'corporate-light',
    name: 'Corporate Light',
    label: 'Light',
    vars: {
      '--bg-primary':      '#f8fafc',
      '--bg-secondary':    '#f1f5f9',
      '--bg-card':         '#ffffff',
      '--bg-hover':        '#e2e8f0',
      '--border':          '#e2e8f0',
      '--text-primary':    '#0f172a',
      '--text-secondary':  '#475569',
      '--text-muted':      '#94a3b8',
      '--accent':          '#1e3a5f',
      '--accent-light':    '#2563eb',
      '--accent-bg':       'rgba(30,58,95,0.08)',
      '--chart-1':         '#1e3a5f',
      '--chart-2':         '#2563eb',
      '--chart-3':         '#0d9488',
      '--chart-4':         '#7c3aed',
      '--chart-5':         '#ea580c',
      '--shadow':          '0 2px 12px rgba(0,0,0,0.08)',
      '--glass':           'none',
      '--sidebar-bg':      '#ffffff',
      '--header-bg':       '#ffffff',
      '--geo-land-data':   '#b8cce8',
    },
  },
  {
    id: 'gradient-modern',
    name: 'Gradient Modern',
    label: 'Gradient',
    vars: {
      '--bg-primary':      '#0f0c29',
      '--bg-secondary':    '#1a1040',
      '--bg-card':         'rgba(255,255,255,0.05)',
      '--bg-hover':        'rgba(255,255,255,0.09)',
      '--border':          'rgba(255,255,255,0.12)',
      '--text-primary':    '#f8fafc',
      '--text-secondary':  '#c4b5fd',
      '--text-muted':      '#7c6fcd',
      '--accent':          '#a855f7',
      '--accent-light':    '#d946ef',
      '--accent-bg':       'rgba(168,85,247,0.15)',
      '--chart-1':         '#a855f7',
      '--chart-2':         '#06b6d4',
      '--chart-3':         '#f43f5e',
      '--chart-4':         '#10b981',
      '--chart-5':         '#fbbf24',
      '--shadow':          '0 8px 32px rgba(168,85,247,0.2)',
      '--glass':           'blur(12px)',
      '--sidebar-bg':      'rgba(15,12,41,0.85)',
      '--header-bg':       'rgba(15,12,41,0.9)',
      '--geo-land-data':   '#3d2a6e',
    },
  },
  {
    id: 'fintech-green',
    name: 'Fintech Green',
    label: 'Fintech',
    vars: {
      '--bg-primary':      '#0a0e17',
      '--bg-secondary':    '#0d1220',
      '--bg-card':         '#111827',
      '--bg-hover':        '#1a2535',
      '--border':          '#1f2d3d',
      '--text-primary':    '#e2e8f0',
      '--text-secondary':  '#6ee7b7',
      '--text-muted':      '#4b7a5e',
      '--accent':          '#22c55e',
      '--accent-light':    '#4ade80',
      '--accent-bg':       'rgba(34,197,94,0.1)',
      '--chart-1':         '#22c55e',
      '--chart-2':         '#16a34a',
      '--chart-3':         '#06b6d4',
      '--chart-4':         '#84cc16',
      '--chart-5':         '#f59e0b',
      '--shadow':          '0 4px 24px rgba(34,197,94,0.15)',
      '--glass':           'none',
      '--sidebar-bg':      '#080c14',
      '--header-bg':       '#080c14',
      '--geo-land-data':   '#0d3320',
    },
  },
  {
    id: 'minimal-slate',
    name: 'Minimal Slate',
    label: 'Slate',
    vars: {
      '--bg-primary':      '#f1f5f9',
      '--bg-secondary':    '#e2e8f0',
      '--bg-card':         '#ffffff',
      '--bg-hover':        '#f8fafc',
      '--border':          '#cbd5e1',
      '--text-primary':    '#1e293b',
      '--text-secondary':  '#475569',
      '--text-muted':      '#94a3b8',
      '--accent':          '#f97316',
      '--accent-light':    '#fb923c',
      '--accent-bg':       'rgba(249,115,22,0.1)',
      '--chart-1':         '#f97316',
      '--chart-2':         '#0ea5e9',
      '--chart-3':         '#8b5cf6',
      '--chart-4':         '#10b981',
      '--chart-5':         '#ec4899',
      '--shadow':          '0 2px 8px rgba(0,0,0,0.06)',
      '--glass':           'none',
      '--sidebar-bg':      '#e2e8f0',
      '--header-bg':       '#ffffff',
      '--geo-land-data':   '#fcd8b8',
    },
  },
]

export const defaultTheme = themes[0]
